# --- Database Configurations ---
spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/emergency_mentalwellbeingauthentication  # MongoDB URI
   database: emergency_mentalwellbeingauthentication

      # Additional MongoDB connection configurations (if needed):
      # authentication-database: admin
      # username: your_username
      # password: your_password

    # MongoDB Specific Properties (Optional)
#    max-wait-time: 2000  # Maximum time to wait for a MongoDB connection
#    connections-per-host: 100  # Max number of connections per host
#    min-connections-per-host: 10  # Minimum connections per host

# --- Server Error Configurations ---
 server:
  error:
   include-binding-errors: never
   include-message: never
   include-stacktrace: never
   include-exception: false
   whitelabel:
    enabled: false
    path: /error
 port: 8080  # Standard port for production


# --- Security Configurations ---
 security:
  user:
   name: ${ADMIN_USERNAME}  # Use environment variable for admin username
   password: ${ADMIN_PASSWORD}  # Use environment variable for admin password
  oauth2:
   client:
    registration:
     google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      scope: email, profile
      redirect-uri: "{baseUrl}/login/oauth2/code/google"
     github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_SECRET_KEY}
      scope: user, repo
      redirect-uri: "{baseUrl}/login/oauth2/code/github"


# --- Logging Configurations ---
logging:
  file:
    name: logs/application-prod.log  # Save logs to a file
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# --- Actuator Monitoring ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # Limit exposed endpoints in production
  endpoint:
    health:
      show-details: never  # Do not show health details in production