# --- Profiles for Environment Management ---
spring:
  application:
    name: Emergency and Mental Wellbeing Authentication  # Application name
  profiles:
    active: ${ENV:development}  # Active profile for environments (e.g., development, production)