# --- Database Configurations ---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/emergency_mentalwellbeingauthentication  # MongoDB URI
      database: emergency_mentalwellbeingauthentication
      auto-index-creation: true


# --- Server Error Configurations ---
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true
    whitelabel: # Custom Error Pages Configuration
      enabled: false  # Disable the default error page
    path: /error  # Custom error handling endpoint
  port: 8080  # Server port configuration


# --- DevTools ---
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true